# Generated by Django 3.1.1 on 2021-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210205_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='music.Song'),
        ),
    ]
